name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name:  Print the secret
        run: echo ${{ secrets.SOME_SECRET }}

      - name: Print the variable
        run: echo ${{ vars.SOME_VAR }}
