name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  cd:
#    if: (github.ref == 'refs/heads/main' && github.event_name == 'push')
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # could be another images registry
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        run: echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Print image tag
        run: echo $SHORT_SHA

      - name: Build and push
        env:
            SHORT_SHA: ${{ env.SHORT_SHA }}
            ECR_REGISTRY: bogdanserdinov
            ECR_REPOSITORY: playground
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:prod-$SHORT_SHA .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:prod-$SHORT_SHA

      - name: Logout of DockerHub
        run: docker logout

#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          push: true
#          tags: playground:prod-$SHORT_SHA
