name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    steps:
      - name:  Print the secret
        run: echo ${{ secrets.SOME_SECRET }}

  print-vars:
    needs: print-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Print the variable
        run: echo ${{ vars.SOME_VAR }}
